DEFAULT_IT_QUERIES = [
    "python developer",
    "python backend developer",
    "django developer",
    "flask developer",
    "fastapi developer",
    "data engineer",
    "backend developer",
    "java developer",
    "spring developer",
    "kotlin developer",
    "scala developer",
    "golang developer",
    "php developer",
    "laravel developer",
    "node.js developer",
    "nestjs developer",
    ".net developer",
    "c# developer",
    "c++ developer",
    "rust developer",
    "frontend developer",
    "javascript developer",
    "typescript developer",
    "react developer",
    "vue developer",
    "angular developer",
    "fullstack developer",
    "mobile developer",
    "android developer",
    "ios developer",
    "react native developer",
    "flutter developer",
    "data analyst",
    "product analyst",
    "business analyst it",
    "system analyst",
    "sql developer",
    "bi analyst",
    "power bi",
    "tableau",
    "data scientist",
    "ml engineer",
    "machine learning engineer",
    "deep learning engineer",
    "nlp engineer",
    "computer vision engineer",
    "mle",
    "ai engineer",
    "qa engineer",
    "qa automation engineer",
    "manual qa",
    "test engineer",
    "sdet",
    "devops engineer",
    "site reliability engineer",
    "platform engineer",
    "cloud engineer",
    "kubernetes engineer",
    "docker engineer",
    "terraform engineer",
    "database administrator",
    "postgresql dba",
    "etl developer",
    "data platform engineer",
    "security engineer",
    "application security engineer",
    "penetration tester",
    "information security engineer",
    "product manager it",
    "project manager it",
    "scrum master",
    "tech lead",
    "solution architect",
    "software architect",
    "1c developer",
]
